# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edge_mst_hclust_impl <- function(from, to, weight, n_nodes) {
    .Call('_lineage_edge_mst_hclust_impl', PACKAGE = 'lineage', from, to, weight, n_nodes)
}

